set nocompatible " disable vi mode
set backspace=2 " backspace configuration
set number " line numbers on the left
set autoindent
set smartindent
set incsearch " move cursor while typing search pattern
set hlsearch
set smartcase
set showcmd " show commands while typing them
set laststatus=2 " always display the status bar
set statusline=[%02n]\ %f\ %(\[%M%R%H]%)\ %y\ %{''.&fileencoding}\ %=\ %4l,%02c%2V\ %P%*
set splitbelow " new split buffers are below the current one
set splitright " new vertical split buffer are on the right of the current one
set history=1000 " bigger history
set wildmenu " display a menu when hitting <TAB>
set wildmode=longest:full " display wildmenu even with commands
set scrolloff=3 " maintain context around the cursor when scrolling
set list listchars=tab:»·,trail:·,extends:…,nbsp:‗ " indicate spaces spaces
syntax on

set guifont=guifont=Monaco:h10
set guioptions-=m
set guioptions-=T
set guioptions-=l
set guioptions-=L
set guioptions-=r
set guioptions-=R

set expandtab
set sw=2
set sts=2

colorscheme spacegray
set ic

" unbind arrow keys
for prefix in ['i', 'n', 'v']
  for key in ['<Up>', '<Down>', '<Left>', '<Right>']
    exe prefix . "noremap " . key . " <Nop>"
  endfor
endfor

" make sure color is enabled on ubuntu
if $COLORTERM == 'gnome-terminal'
  set t_Co=256
endif

" unhighlight the search results when the keyboard is idle
autocmd CursorHold,CursorHoldI * nohls | redraw

" map <Esc> to jk
imap jk <Esc>

" map ; to :
nmap ; :
